version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 9876:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: invoicesDB

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
